apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-mysql
  namespace: jhipster-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp1-mysql
  template:
    metadata:
      labels:
        app: myapp1-mysql
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: mysql
          image: mysql:8.0.28
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: myapp1
          args:
            - --lower_case_table_names=1
            - --skip-ssl
            - --character_set_server=utf8mb4
            - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp1-mysql
  namespace: jhipster-project
spec:
  selector:
    app: myapp1-mysql
  ports:
    - port: 3306
