commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: jhipster-project

resources:
  - namespace.yml
  # Individual apps
  - myapp-k8s/myapp-deployment.yml
  - myapp-k8s/myapp-service.yml
  - myapp-k8s/myapp-mysql.yml
  - myapp-k8s/myapp-destination-rule.yml
  - myapp-k8s/myapp-virtual-service.yml
  - myapp1-k8s/myapp1-deployment.yml
  - myapp1-k8s/myapp1-service.yml
  - myapp1-k8s/myapp1-mysql.yml
  - myapp1-k8s/myapp1-destination-rule.yml
  - myapp1-k8s/myapp1-virtual-service.yml
  - myapp2-k8s/myapp2-deployment.yml
  - myapp2-k8s/myapp2-service.yml
  - myapp2-k8s/myapp2-mysql.yml
  - myapp2-k8s/myapp2-destination-rule.yml
  - myapp2-k8s/myapp2-virtual-service.yml
  # service discovery eureka/consul
  # istio
  - istio-k8s/grafana-gateway.yml
  - istio-k8s/zipkin-gateway.yml
  - istio-k8s/kiali-gateway.yml

patchesJson6902:
  - target:
      version: v1
      kind: Namespace
      name: jhipster-project
    path: patch-k8s/istio-label.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
      name: grafana-observability-gateway
      namespace: jhipster-project
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      name: grafana-gw-virtualservice
      kind: VirtualService
      namespace: jhipster-project
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
      name: kiali-observability-gateway
      namespace: jhipster-project
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      name: kiali-gw-virtualservice
      kind: VirtualService
      namespace: jhipster-project
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
      name: zipkin-observability-gateway
      namespace: jhipster-project
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      name: zipkin-gw-virtualservice
      kind: VirtualService
      namespace: jhipster-project
    path: patch-k8s/istio-namespace.yml
